# Generated by Django 3.0.8 on 2021-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=20, null=True)),
                ('l_name', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=144, null=True)),
                ('phone_number', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
                ('time', models.IntegerField(null=True)),
                ('special', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
